### ISSUE TITLE
Team Image Fails to Show Up Properly

### ISSUE THREAD

**Issue by ez500** [frc461/frc461.github.io#1]
Image of the team (alted as "Team image") does not show up properly. 

![image](https://github.com/frc461/frc461.github.io/assets/46542767/55797a65-4f91-4065-bb30-df72e934c1cd)

**Comment by yeoms25** [comment]
I know lol
It shows up on the jekyll serve properly but it doesn't on github
I should probably download the image and link it
Super

2024년 2월 18일 (일) 오전 2:15, ez500 ***@***.***>님이 작성:

**Comment by ez500** [comment]
lol we can use issues to develop the website more, maybe we could tell people to report problems/suggestions here

**Comment by ez500** [comment]
Branches are also a good way to solve particular issues, and when the issue is fixed, just merge the issue branch into main via pull request (PR). the corresponding issue will automatically close and the branch will automatically be deleted.
