### ISSUE TITLE
Light/Dark Mode

### ISSUE THREAD

**Issue by ez500** [frc461/frc461.github.io#3]
Maybe add this feature (low priority)

**Comment by codemob-dev** [comment]
I got this working

**Comment by ez500** [comment]
bugfixing time 

![image](https://github.com/frc461/frc461.github.io/assets/46542767/f12aca0a-1f62-4e1f-9bd9-9b5fd20bf862)

**Comment by ez500** [comment]
Also maybe not totally black, probably dark blue or dark gray or something

**Comment by codemob-dev** [comment]
The weird white bands are fixed.
